function out1 = getH04Iiwa(q1,q2,q3,q4)
%GETH04IIWA
%    OUT1 = GETH04IIWA(Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-May-2017 10:59:46

t2 = cos(q1);
t3 = sin(q4);
t4 = sin(q1);
t5 = sin(q3);
t6 = t4.*t5;
t7 = cos(q2);
t8 = cos(q3);
t9 = t6-t2.*t7.*t8;
t10 = cos(q4);
t11 = sin(q2);
t12 = t2.*t5;
t13 = t4.*t7.*t8;
t14 = t12+t13;
out1 = reshape([-t9.*t10+t2.*t3.*t11,t10.*t14+t3.*t4.*t11,t3.*t7-t8.*t10.*t11,0.0,t3.*t9+t2.*t10.*t11,-t3.*t14+t4.*t10.*t11,t7.*t10+t3.*t8.*t11,0.0,t4.*t8+t2.*t5.*t7,-t2.*t8+t4.*t5.*t7,-t5.*t11,0.0,t2.*t11.*4.2e2,t4.*t11.*4.2e2,t7.*4.2e2+3.6e2,1.0],[4,4]);
