function out1 = getH02Iiwa(q1,q2)
%GETH02IIWA
%    OUT1 = GETH02IIWA(Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-May-2017 10:59:32

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
out1 = reshape([t2.*t3,t3.*t4,-t5,0.0,-t2.*t5,-t4.*t5,-t3,0.0,-t4,t2,0.0,0.0,0.0,0.0,3.6e2,1.0],[4,4]);
