function out1 = getH03Iiwa(q1,q2,q3)
%GETH03IIWA
%    OUT1 = GETH03IIWA(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-May-2017 10:59:41

t2 = cos(q3);
t3 = sin(q1);
t4 = cos(q1);
t5 = cos(q2);
t6 = sin(q3);
t7 = sin(q2);
out1 = reshape([-t3.*t6+t2.*t4.*t5,t4.*t6+t2.*t3.*t5,-t2.*t7,0.0,-t2.*t3-t4.*t5.*t6,t2.*t4-t3.*t5.*t6,t6.*t7,0.0,t4.*t7,t3.*t7,t5,0.0,t4.*t7.*4.2e2,t3.*t7.*4.2e2,t5.*4.2e2+3.6e2,1.0],[4,4]);
