function out1 = getH01Iiwa(q1)
%GETH01IIWA
%    OUT1 = GETH01IIWA(Q1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-May-2017 10:59:22

t2 = sin(q1);
t3 = cos(q1);
out1 = reshape([t3,t2,0.0,0.0,-t2,t3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.6e2,1.0],[4,4]);
