function out1 = getH05Iiwa(q1,q2,q3,q4,q5)
%GETH05IIWA
%    OUT1 = GETH05IIWA(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-May-2017 10:59:50

t2 = cos(q1);
t3 = cos(q3);
t4 = sin(q1);
t5 = cos(q2);
t6 = sin(q3);
t7 = sin(q5);
t8 = cos(q4);
t9 = t4.*t6;
t19 = t2.*t3.*t5;
t10 = t9-t19;
t11 = t8.*t10;
t12 = sin(q2);
t13 = sin(q4);
t14 = t11-t2.*t12.*t13;
t15 = cos(q5);
t16 = t3.*t4;
t17 = t2.*t5.*t6;
t18 = t16+t17;
t20 = t2.*t6;
t21 = t3.*t4.*t5;
t22 = t20+t21;
t23 = t8.*t22;
t24 = t4.*t12.*t13;
t25 = t23+t24;
t26 = t2.*t3;
t27 = t26-t4.*t5.*t6;
t28 = t5.*t13;
t29 = t28-t3.*t8.*t12;
out1 = reshape([-t7.*t18-t14.*t15,t7.*t27+t15.*t25,t15.*t29+t6.*t7.*t12,0.0,t7.*t14-t15.*t18,-t7.*t25+t15.*t27,-t7.*t29+t6.*t12.*t15,0.0,t10.*t13+t2.*t8.*t12,-t13.*t22+t4.*t8.*t12,t5.*t8+t3.*t12.*t13,0.0,t2.*t12.*4.2e2+t10.*t13.*4.0e2+t2.*t8.*t12.*4.0e2,t4.*t12.*4.2e2-t13.*t22.*4.0e2+t4.*t8.*t12.*4.0e2,t5.*4.2e2+t5.*t8.*4.0e2+t3.*t12.*t13.*4.0e2+3.6e2,1.0],[4,4]);
