function out1 = Q_1_5(a,b,c,q1,q2,q3,q4)
%Q_1_52
%    OUT1 = Q_1_52(A,B,C,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Apr-2017 13:50:55

t2 = cos(q1);
t3 = cos(q4);
t4 = sin(q3);
t5 = cos(q2);
t6 = cos(q3);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q4);
t10 = cos(a);
t11 = sin(c);
t12 = cos(c);
t13 = sin(a);
t14 = sin(b);
t15 = t11.*t13;
t16 = t10.*t12.*t14;
t17 = t15+t16;
t18 = t10.*t11;
t19 = t18-t12.*t13.*t14;
t20 = cos(b);
out1 = angle(-t17.*(t3.*(t4.*t7-t2.*t5.*t6)-t2.*t8.*t9)-t19.*(t3.*(t2.*t4+t5.*t6.*t7)+t7.*t8.*t9)-t17.*(t6.*t7+t2.*t4.*t5).*1i-t19.*(t2.*t6-t4.*t5.*t7).*1i+t12.*t20.*(t5.*t9-t3.*t6.*t8)+t4.*t8.*t12.*t20.*1i);
