function out1 = Q_1_1(a,b,c,swivel,x,y,z)
%Q_1_1
%    OUT1 = Q_1_1(A,B,C,SWIVEL,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Apr-2017 08:41:05

t3 = sin(a);
t4 = sin(c);
t5 = cos(a);
t6 = cos(c);
t7 = sin(b);
t10 = t4.*t5.*1.52e2;
t11 = t3.*t6.*t7.*1.52e2;
t12 = t10-t11+y;
t2 = abs(t12);
t14 = t3.*t4.*1.52e2;
t15 = t5.*t6.*t7.*1.52e2;
t16 = t14+t15-x;
t8 = abs(t16);
t18 = cos(b);
t19 = t6.*t18.*1.52e2;
t20 = t19-z+3.6e2;
t9 = abs(t20);
t13 = t2.^2;
t17 = t8.^2;
t21 = t9.^2;
t22 = t13+t17+t21+1.64e4;
t23 = t13+t17+t21;
t24 = 1.0./t23;
t33 = t12.*t20;
t25 = abs(t33);
t36 = t16.*t20;
t26 = abs(t36);
t27 = 1.0./t23.^2;
t28 = t12.^2;
t29 = t24.*t28;
t30 = t16.^2;
t31 = t24.*t30;
t32 = t29+t31;
t34 = t25.^2;
t35 = t27.*t34;
t37 = t26.^2;
t38 = t27.*t37;
t39 = t32.^2;
t40 = t35+t38+t39;
t41 = 1.0./sqrt(t40);
t42 = t22.^2;
t43 = t24.*t42.*(-1.0./4.0)+1.764e5;
t44 = sqrt(t43);
t45 = sin(swivel);
t46 = t20.^2;
t47 = 1.0./t23.^(3.0./2.0);
t48 = 1.0./sqrt(t23);
t49 = cos(swivel);
out1 = angle(t44.*(t45.*(t12.*t32.*t41.*t48+t12.*t41.*t46.*t47)-t16.*t20.*t24.*t41.*t49)+t44.*(t45.*(t16.*t32.*t41.*t48+t16.*t41.*t46.*t47)+t12.*t20.*t24.*t41.*t49).*1i+t12.*t22.*t24.*5.0e-1i-t16.*t22.*t24.*(1.0./2.0));
