function out1 = Q_1_7(a,b,c,q1,q2,q3,q4)
%Q_1_72
%    OUT1 = Q_1_72(A,B,C,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Apr-2017 13:52:16

t2 = cos(q1);
t3 = sin(q4);
t4 = sin(q3);
t5 = cos(q2);
t6 = cos(q3);
t7 = sin(q1);
t8 = cos(q4);
t9 = sin(q2);
t10 = cos(a);
t11 = cos(c);
t12 = sin(a);
t13 = sin(b);
t14 = sin(c);
t15 = t5.*t8;
t16 = t3.*t6.*t9;
t17 = t15+t16;
t18 = cos(b);
t19 = t4.*t7;
t20 = t19-t2.*t5.*t6;
t21 = t3.*t20;
t22 = t2.*t8.*t9;
t23 = t21+t22;
t24 = t2.*t4;
t25 = t5.*t6.*t7;
t26 = t24+t25;
t27 = t3.*t26;
t28 = t27-t7.*t8.*t9;
out1 = angle(t23.*(t11.*t12-t10.*t13.*t14).*-1i-t28.*(t10.*t11+t12.*t13.*t14).*1i+t13.*t17+t14.*t17.*t18.*1i-t10.*t18.*t23+t12.*t18.*t28);
