function [proximitySensors_handles, proximitySensors_names, ret] = vrep_getProximitySensorsHandles(clientID,vrep)
% retrieve proximity Sensors handles from vrep scene


proximitySensors_names = {'proxSensor_KMR_scene_01';...
                          'proxSensor_KMR_scene_02';...
                          'proxSensor_KMR_scene_03';...
                          'proxSensor_KMR_scene_04';...
                          'proxSensor_KMR_scene_05';...
                          'proxSensor_KMR_link3';...
                          'proxSensor_KMR_link4';...
                          'proxSensor_KMR_link5';...
                          'proxSensor_KMR_link6';...
                          'proxSensor_KMR_linkFlange';...
                          'proxSensor_link0_scene';...
                          'proxSensor_link1_scene';...
                          'proxSensor_link2_scene';...
                          'proxSensor_link3_scene';...
                          'proxSensor_link4_scene';...
                          'proxSensor_link5_scene';...
                          'proxSensor_link6_scene';...
                          'proxSensor_EE_KMR';...
                          'proxSensor_EE_link0';...
                          'proxSensor_EE_link1';...
                          'proxSensor_EE_link2'};


proximitySensors_handles = zeros(length(proximitySensors_names),1);

for i = 1:length(proximitySensors_names)
    [ret,proximitySensors_handles(i)] = vrep.simxGetObjectHandle(clientID,proximitySensors_names{i},vrep.simx_opmode_blocking);
end



end

