function [distancesHandles,distancesNames, ret] = vrep_getDistancesHandles(clientID,vrep)

% retrieves distances handles in vector distancesHandles and their corresponding
% names in cell array distancesNames
    
    distancesHandles = zeros(17,1);
    [ret,distancesHandles(1)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_link3_KMR', vrep.simx_opmode_blocking);
    [ret,distancesHandles(2)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_link4_KMR', vrep.simx_opmode_blocking);
    [ret,distancesHandles(3)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_link5_KMR', vrep.simx_opmode_blocking);
    [ret,distancesHandles(4)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_link6_KMR', vrep.simx_opmode_blocking);
    [ret,distancesHandles(5)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_linkFlange_KMR', vrep.simx_opmode_blocking);
    [ret,distancesHandles(6)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_EE_KMR', vrep.simx_opmode_blocking);
    [ret,distancesHandles(7)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_EE_link0', vrep.simx_opmode_blocking);
    [ret,distancesHandles(8)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_EE_link1', vrep.simx_opmode_blocking);
    [ret,distancesHandles(9)]=vrep.simxGetDistanceHandle(clientID, 'AutoCol_Distance_EE_link2', vrep.simx_opmode_blocking); % we assume here that the EE can't collide with the forearm (which may be completely wrong)
    
    [ret,distancesHandles(10)]=vrep.simxGetDistanceHandle(clientID, 'Col_Distance_KMR_scene', vrep.simx_opmode_blocking);
    [ret,distancesHandles(11)]=vrep.simxGetDistanceHandle(clientID, 'Col_Distance_link0_scene', vrep.simx_opmode_blocking);
    [ret,distancesHandles(12)]=vrep.simxGetDistanceHandle(clientID, 'Col_Distance_link1_scene', vrep.simx_opmode_blocking);
    [ret,distancesHandles(13)]=vrep.simxGetDistanceHandle(clientID, 'Col_Distance_link2_scene', vrep.simx_opmode_blocking);
    [ret,distancesHandles(14)]=vrep.simxGetDistanceHandle(clientID, 'Col_Distance_link3_scene', vrep.simx_opmode_blocking);
    [ret,distancesHandles(15)]=vrep.simxGetDistanceHandle(clientID, 'Col_Distance_link4_scene', vrep.simx_opmode_blocking);
    [ret,distancesHandles(16)]=vrep.simxGetDistanceHandle(clientID, 'Col_Distance_link5_scene', vrep.simx_opmode_blocking);
    [ret,distancesHandles(17)]=vrep.simxGetDistanceHandle(clientID, 'Col_Distance_link6_scene', vrep.simx_opmode_blocking); 
    
    distancesNames = {'AutoCol_Distance_link3_KMR';...
                      'AutoCol_Distance_link4_KMR';...
                      'AutoCol_Distance_link5_KMR';...
                      'AutoCol_Distance_link6_KMR';...
                      'AutoCol_Distance_linkFlange_KMR';...
                      'AutoCol_Distance_EE_KMR';...
                      'AutoCol_Distance_EE_link0';...
                      'AutoCol_Distance_EE_link1';...
                      'AutoCol_Distance_EE_link2';...
                      'Col_Distance_KMR_scene';...
                      'Col_Distance_link0_scene';...
                      'Col_Distance_link1_scene';...
                      'Col_Distance_link2_scene';...
                      'Col_Distance_link3_scene';...
                      'Col_Distance_link4_scene';...
                      'Col_Distance_link5_scene';...
                      'Col_Distance_link6_scene'};
    
    


end


